/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PayPerView {
  export type FilmStruct = {
    filmmaker: AddressLike;
    priceWei: BigNumberish;
    exists: boolean;
  };

  export type FilmStructOutput = [
    filmmaker: string,
    priceWei: bigint,
    exists: boolean
  ] & { filmmaker: string; priceWei: bigint; exists: boolean };
}

export interface PayPerViewInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "PLATFORM_FEE_BPS"
      | "buyAccess"
      | "getFilm"
      | "hasAccess"
      | "owner"
      | "registerFilm"
      | "renounceOwnership"
      | "setFilmPrice"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessPurchased"
      | "FilmPriceUpdated"
      | "FilmRegistered"
      | "OwnershipTransferred"
      | "RevenueSplit"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyAccess",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFilm",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccess",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerFilm",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFilmPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyAccess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFilm", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasAccess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerFilm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFilmPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AccessPurchasedEvent {
  export type InputTuple = [
    filmId: BigNumberish,
    buyer: AddressLike,
    pricePaid: BigNumberish,
    filmmaker: AddressLike,
    filmmakerShare: BigNumberish,
    platformFee: BigNumberish
  ];
  export type OutputTuple = [
    filmId: bigint,
    buyer: string,
    pricePaid: bigint,
    filmmaker: string,
    filmmakerShare: bigint,
    platformFee: bigint
  ];
  export interface OutputObject {
    filmId: bigint;
    buyer: string;
    pricePaid: bigint;
    filmmaker: string;
    filmmakerShare: bigint;
    platformFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FilmPriceUpdatedEvent {
  export type InputTuple = [
    filmId: BigNumberish,
    oldPrice: BigNumberish,
    newPrice: BigNumberish
  ];
  export type OutputTuple = [
    filmId: bigint,
    oldPrice: bigint,
    newPrice: bigint
  ];
  export interface OutputObject {
    filmId: bigint;
    oldPrice: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FilmRegisteredEvent {
  export type InputTuple = [
    filmId: BigNumberish,
    filmmaker: AddressLike,
    priceWei: BigNumberish
  ];
  export type OutputTuple = [
    filmId: bigint,
    filmmaker: string,
    priceWei: bigint
  ];
  export interface OutputObject {
    filmId: bigint;
    filmmaker: string;
    priceWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevenueSplitEvent {
  export type InputTuple = [
    creator: AddressLike,
    creatorShare: BigNumberish,
    platformFee: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    creatorShare: bigint,
    platformFee: bigint
  ];
  export interface OutputObject {
    creator: string;
    creatorShare: bigint;
    platformFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PayPerView extends BaseContract {
  connect(runner?: ContractRunner | null): PayPerView;
  waitForDeployment(): Promise<this>;

  interface: PayPerViewInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  buyAccess: TypedContractMethod<[filmId: BigNumberish], [void], "payable">;

  getFilm: TypedContractMethod<
    [filmId: BigNumberish],
    [PayPerView.FilmStructOutput],
    "view"
  >;

  hasAccess: TypedContractMethod<
    [user: AddressLike, filmId: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerFilm: TypedContractMethod<
    [filmId: BigNumberish, priceWei: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFilmPrice: TypedContractMethod<
    [filmId: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyAccess"
  ): TypedContractMethod<[filmId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getFilm"
  ): TypedContractMethod<
    [filmId: BigNumberish],
    [PayPerView.FilmStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasAccess"
  ): TypedContractMethod<
    [user: AddressLike, filmId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerFilm"
  ): TypedContractMethod<
    [filmId: BigNumberish, priceWei: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFilmPrice"
  ): TypedContractMethod<
    [filmId: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AccessPurchased"
  ): TypedContractEvent<
    AccessPurchasedEvent.InputTuple,
    AccessPurchasedEvent.OutputTuple,
    AccessPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "FilmPriceUpdated"
  ): TypedContractEvent<
    FilmPriceUpdatedEvent.InputTuple,
    FilmPriceUpdatedEvent.OutputTuple,
    FilmPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FilmRegistered"
  ): TypedContractEvent<
    FilmRegisteredEvent.InputTuple,
    FilmRegisteredEvent.OutputTuple,
    FilmRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RevenueSplit"
  ): TypedContractEvent<
    RevenueSplitEvent.InputTuple,
    RevenueSplitEvent.OutputTuple,
    RevenueSplitEvent.OutputObject
  >;

  filters: {
    "AccessPurchased(uint256,address,uint256,address,uint256,uint256)": TypedContractEvent<
      AccessPurchasedEvent.InputTuple,
      AccessPurchasedEvent.OutputTuple,
      AccessPurchasedEvent.OutputObject
    >;
    AccessPurchased: TypedContractEvent<
      AccessPurchasedEvent.InputTuple,
      AccessPurchasedEvent.OutputTuple,
      AccessPurchasedEvent.OutputObject
    >;

    "FilmPriceUpdated(uint256,uint256,uint256)": TypedContractEvent<
      FilmPriceUpdatedEvent.InputTuple,
      FilmPriceUpdatedEvent.OutputTuple,
      FilmPriceUpdatedEvent.OutputObject
    >;
    FilmPriceUpdated: TypedContractEvent<
      FilmPriceUpdatedEvent.InputTuple,
      FilmPriceUpdatedEvent.OutputTuple,
      FilmPriceUpdatedEvent.OutputObject
    >;

    "FilmRegistered(uint256,address,uint256)": TypedContractEvent<
      FilmRegisteredEvent.InputTuple,
      FilmRegisteredEvent.OutputTuple,
      FilmRegisteredEvent.OutputObject
    >;
    FilmRegistered: TypedContractEvent<
      FilmRegisteredEvent.InputTuple,
      FilmRegisteredEvent.OutputTuple,
      FilmRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RevenueSplit(address,uint256,uint256)": TypedContractEvent<
      RevenueSplitEvent.InputTuple,
      RevenueSplitEvent.OutputTuple,
      RevenueSplitEvent.OutputObject
    >;
    RevenueSplit: TypedContractEvent<
      RevenueSplitEvent.InputTuple,
      RevenueSplitEvent.OutputTuple,
      RevenueSplitEvent.OutputObject
    >;
  };
}
