/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ProofRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getManifest"
      | "owner"
      | "registerManifest"
      | "renounceOwnership"
      | "transferOwnership"
      | "verifyFragment"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ManifestRegistered"
      | "ManifestUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getManifest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerManifest",
    values: [BigNumberish, BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyFragment",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getManifest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerManifest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyFragment",
    data: BytesLike
  ): Result;
}

export namespace ManifestRegisteredEvent {
  export type InputTuple = [
    filmId: BigNumberish,
    registrant: AddressLike,
    merkleRoot: BytesLike,
    fragmentCount: BigNumberish,
    manifestArweaveTx: string
  ];
  export type OutputTuple = [
    filmId: bigint,
    registrant: string,
    merkleRoot: string,
    fragmentCount: bigint,
    manifestArweaveTx: string
  ];
  export interface OutputObject {
    filmId: bigint;
    registrant: string;
    merkleRoot: string;
    fragmentCount: bigint;
    manifestArweaveTx: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManifestUpdatedEvent {
  export type InputTuple = [
    filmId: BigNumberish,
    updater: AddressLike,
    oldRoot: BytesLike,
    newRoot: BytesLike,
    fragmentCount: BigNumberish,
    manifestArweaveTx: string
  ];
  export type OutputTuple = [
    filmId: bigint,
    updater: string,
    oldRoot: string,
    newRoot: string,
    fragmentCount: bigint,
    manifestArweaveTx: string
  ];
  export interface OutputObject {
    filmId: bigint;
    updater: string;
    oldRoot: string;
    newRoot: string;
    fragmentCount: bigint;
    manifestArweaveTx: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProofRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ProofRegistry;
  waitForDeployment(): Promise<this>;

  interface: ProofRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getManifest: TypedContractMethod<
    [filmId: BigNumberish],
    [
      [string, bigint, string, string, bigint, bigint] & {
        merkleRoot: string;
        fragmentCount: bigint;
        manifestArweaveTx: string;
        registrant: string;
        registeredAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerManifest: TypedContractMethod<
    [
      filmId: BigNumberish,
      merkleRoot: BytesLike,
      fragmentCount: BigNumberish,
      manifestArweaveTx: string
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyFragment: TypedContractMethod<
    [
      filmId: BigNumberish,
      fragmentIndex: BigNumberish,
      leafHash: BytesLike,
      proof: BytesLike[]
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getManifest"
  ): TypedContractMethod<
    [filmId: BigNumberish],
    [
      [string, bigint, string, string, bigint, bigint] & {
        merkleRoot: string;
        fragmentCount: bigint;
        manifestArweaveTx: string;
        registrant: string;
        registeredAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerManifest"
  ): TypedContractMethod<
    [
      filmId: BigNumberish,
      merkleRoot: BytesLike,
      fragmentCount: BigNumberish,
      manifestArweaveTx: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyFragment"
  ): TypedContractMethod<
    [
      filmId: BigNumberish,
      fragmentIndex: BigNumberish,
      leafHash: BytesLike,
      proof: BytesLike[]
    ],
    [boolean],
    "view"
  >;

  getEvent(
    key: "ManifestRegistered"
  ): TypedContractEvent<
    ManifestRegisteredEvent.InputTuple,
    ManifestRegisteredEvent.OutputTuple,
    ManifestRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ManifestUpdated"
  ): TypedContractEvent<
    ManifestUpdatedEvent.InputTuple,
    ManifestUpdatedEvent.OutputTuple,
    ManifestUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "ManifestRegistered(uint256,address,bytes32,uint256,string)": TypedContractEvent<
      ManifestRegisteredEvent.InputTuple,
      ManifestRegisteredEvent.OutputTuple,
      ManifestRegisteredEvent.OutputObject
    >;
    ManifestRegistered: TypedContractEvent<
      ManifestRegisteredEvent.InputTuple,
      ManifestRegisteredEvent.OutputTuple,
      ManifestRegisteredEvent.OutputObject
    >;

    "ManifestUpdated(uint256,address,bytes32,bytes32,uint256,string)": TypedContractEvent<
      ManifestUpdatedEvent.InputTuple,
      ManifestUpdatedEvent.OutputTuple,
      ManifestUpdatedEvent.OutputObject
    >;
    ManifestUpdated: TypedContractEvent<
      ManifestUpdatedEvent.InputTuple,
      ManifestUpdatedEvent.OutputTuple,
      ManifestUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
