/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Reviews {
  export type ReviewStruct = {
    reviewer: AddressLike;
    rating: BigNumberish;
    comment: string;
    timestamp: BigNumberish;
  };

  export type ReviewStructOutput = [
    reviewer: string,
    rating: bigint,
    comment: string,
    timestamp: bigint
  ] & { reviewer: string; rating: bigint; comment: string; timestamp: bigint };
}

export interface ReviewsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "filmmakerCampaign"
      | "getReview"
      | "getReviewCount"
      | "getReviews"
      | "hasReviewed"
      | "movieTicket"
      | "reviewersByVideo"
      | "submitReview"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ReviewSubmitted" | "ReviewUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "filmmakerCampaign",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReview",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReviewCount",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getReviews", values: [string]): string;
  encodeFunctionData(
    functionFragment: "hasReviewed",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "movieTicket",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reviewersByVideo",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitReview",
    values: [string, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "filmmakerCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getReview", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReviewCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getReviews", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasReviewed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "movieTicket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reviewersByVideo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitReview",
    data: BytesLike
  ): Result;
}

export namespace ReviewSubmittedEvent {
  export type InputTuple = [
    videoHash: string,
    reviewer: AddressLike,
    rating: BigNumberish,
    comment: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    videoHash: string,
    reviewer: string,
    rating: bigint,
    comment: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    videoHash: string;
    reviewer: string;
    rating: bigint;
    comment: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewUpdatedEvent {
  export type InputTuple = [
    videoHash: string,
    reviewer: AddressLike,
    rating: BigNumberish,
    comment: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    videoHash: string,
    reviewer: string,
    rating: bigint,
    comment: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    videoHash: string;
    reviewer: string;
    rating: bigint;
    comment: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Reviews extends BaseContract {
  connect(runner?: ContractRunner | null): Reviews;
  waitForDeployment(): Promise<this>;

  interface: ReviewsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  filmmakerCampaign: TypedContractMethod<[], [string], "view">;

  getReview: TypedContractMethod<
    [videoHash: string, reviewer: AddressLike],
    [Reviews.ReviewStructOutput],
    "view"
  >;

  getReviewCount: TypedContractMethod<[videoHash: string], [bigint], "view">;

  getReviews: TypedContractMethod<
    [videoHash: string],
    [Reviews.ReviewStructOutput[]],
    "view"
  >;

  hasReviewed: TypedContractMethod<
    [videoHash: string, reviewer: AddressLike],
    [boolean],
    "view"
  >;

  movieTicket: TypedContractMethod<[], [string], "view">;

  reviewersByVideo: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [string],
    "view"
  >;

  submitReview: TypedContractMethod<
    [videoHash: string, rating: BigNumberish, comment: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "filmmakerCampaign"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getReview"
  ): TypedContractMethod<
    [videoHash: string, reviewer: AddressLike],
    [Reviews.ReviewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReviewCount"
  ): TypedContractMethod<[videoHash: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReviews"
  ): TypedContractMethod<
    [videoHash: string],
    [Reviews.ReviewStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasReviewed"
  ): TypedContractMethod<
    [videoHash: string, reviewer: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "movieTicket"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reviewersByVideo"
  ): TypedContractMethod<[arg0: string, arg1: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "submitReview"
  ): TypedContractMethod<
    [videoHash: string, rating: BigNumberish, comment: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ReviewSubmitted"
  ): TypedContractEvent<
    ReviewSubmittedEvent.InputTuple,
    ReviewSubmittedEvent.OutputTuple,
    ReviewSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ReviewUpdated"
  ): TypedContractEvent<
    ReviewUpdatedEvent.InputTuple,
    ReviewUpdatedEvent.OutputTuple,
    ReviewUpdatedEvent.OutputObject
  >;

  filters: {
    "ReviewSubmitted(string,address,uint8,string,uint256)": TypedContractEvent<
      ReviewSubmittedEvent.InputTuple,
      ReviewSubmittedEvent.OutputTuple,
      ReviewSubmittedEvent.OutputObject
    >;
    ReviewSubmitted: TypedContractEvent<
      ReviewSubmittedEvent.InputTuple,
      ReviewSubmittedEvent.OutputTuple,
      ReviewSubmittedEvent.OutputObject
    >;

    "ReviewUpdated(string,address,uint8,string,uint256)": TypedContractEvent<
      ReviewUpdatedEvent.InputTuple,
      ReviewUpdatedEvent.OutputTuple,
      ReviewUpdatedEvent.OutputObject
    >;
    ReviewUpdated: TypedContractEvent<
      ReviewUpdatedEvent.InputTuple,
      ReviewUpdatedEvent.OutputTuple,
      ReviewUpdatedEvent.OutputObject
    >;
  };
}
