/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SeederReputationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attestor"
      | "getStats"
      | "owner"
      | "renounceOwnership"
      | "reportSeeding"
      | "scoreOf"
      | "setAttestor"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AttestorUpdated"
      | "OwnershipTransferred"
      | "SeedingReported"
  ): EventFragment;

  encodeFunctionData(functionFragment: "attestor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reportSeeding",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "scoreOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAttestor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "attestor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportSeeding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "scoreOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAttestor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AttestorUpdatedEvent {
  export type InputTuple = [oldAttestor: AddressLike, newAttestor: AddressLike];
  export type OutputTuple = [oldAttestor: string, newAttestor: string];
  export interface OutputObject {
    oldAttestor: string;
    newAttestor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SeedingReportedEvent {
  export type InputTuple = [
    seeder: AddressLike,
    periodId: BigNumberish,
    uptimeSecs: BigNumberish,
    bytesServed: BigNumberish,
    validProofs: BigNumberish
  ];
  export type OutputTuple = [
    seeder: string,
    periodId: bigint,
    uptimeSecs: bigint,
    bytesServed: bigint,
    validProofs: bigint
  ];
  export interface OutputObject {
    seeder: string;
    periodId: bigint;
    uptimeSecs: bigint;
    bytesServed: bigint;
    validProofs: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SeederReputation extends BaseContract {
  connect(runner?: ContractRunner | null): SeederReputation;
  waitForDeployment(): Promise<this>;

  interface: SeederReputationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attestor: TypedContractMethod<[], [string], "view">;

  getStats: TypedContractMethod<
    [seeder: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        uptimeSecs: bigint;
        bytesServed: bigint;
        validProofs: bigint;
        reportCount: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reportSeeding: TypedContractMethod<
    [
      seeder: AddressLike,
      uptimeSecs: BigNumberish,
      bytesServed: BigNumberish,
      validProofs: BigNumberish,
      periodId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  scoreOf: TypedContractMethod<[seeder: AddressLike], [bigint], "view">;

  setAttestor: TypedContractMethod<
    [newAttestor: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attestor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [seeder: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        uptimeSecs: bigint;
        bytesServed: bigint;
        validProofs: bigint;
        reportCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reportSeeding"
  ): TypedContractMethod<
    [
      seeder: AddressLike,
      uptimeSecs: BigNumberish,
      bytesServed: BigNumberish,
      validProofs: BigNumberish,
      periodId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scoreOf"
  ): TypedContractMethod<[seeder: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setAttestor"
  ): TypedContractMethod<[newAttestor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AttestorUpdated"
  ): TypedContractEvent<
    AttestorUpdatedEvent.InputTuple,
    AttestorUpdatedEvent.OutputTuple,
    AttestorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SeedingReported"
  ): TypedContractEvent<
    SeedingReportedEvent.InputTuple,
    SeedingReportedEvent.OutputTuple,
    SeedingReportedEvent.OutputObject
  >;

  filters: {
    "AttestorUpdated(address,address)": TypedContractEvent<
      AttestorUpdatedEvent.InputTuple,
      AttestorUpdatedEvent.OutputTuple,
      AttestorUpdatedEvent.OutputObject
    >;
    AttestorUpdated: TypedContractEvent<
      AttestorUpdatedEvent.InputTuple,
      AttestorUpdatedEvent.OutputTuple,
      AttestorUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SeedingReported(address,uint64,uint64,uint128,uint64)": TypedContractEvent<
      SeedingReportedEvent.InputTuple,
      SeedingReportedEvent.OutputTuple,
      SeedingReportedEvent.OutputObject
    >;
    SeedingReported: TypedContractEvent<
      SeedingReportedEvent.InputTuple,
      SeedingReportedEvent.OutputTuple,
      SeedingReportedEvent.OutputObject
    >;
  };
}
