import fs from "fs";
import path from "path";

/**
 * Exports the compiled contract ABIs into the frontend as a single typed, auto-generated
 * TypeScript module. This keeps the frontend ABIs in lockstep with the real contracts
 * (no hand-maintained drift).
 *
 * Run after compiling:  npm run export:abi   (also runs automatically via `npm run compile`)
 * Output: apps/frontend/lib/contracts/abis.generated.ts
 */

const CONTRACTS = ["MovieTicket", "FilmmakerCampaign", "Reviews", "SeederCredits"] as const;

// exported const name per contract (e.g. MovieTicket -> MOVIE_TICKET_ABI_FULL)
function constName(contract: string): string {
  const snake = contract.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
  return `${snake}_ABI_FULL`;
}

const ARTIFACTS_DIR = path.join(__dirname, "../artifacts/contracts");
// __dirname = packages/contracts/scripts → up 3 to repo root, then into apps/frontend.
const OUT_PATH = path.join(
  __dirname,
  "../../../apps/frontend/lib/contracts/abis.generated.ts"
);

async function main() {
  const blocks: string[] = [];

  for (const name of CONTRACTS) {
    const artifactPath = path.join(ARTIFACTS_DIR, `${name}.sol`, `${name}.json`);
    if (!fs.existsSync(artifactPath)) {
      console.error(`Artifact not found: ${artifactPath}\nRun \`npx hardhat compile\` first.`);
      process.exit(1);
    }
    const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
    const abiJson = JSON.stringify(artifact.abi, null, 2);
    blocks.push(`export const ${constName(name)} = ${abiJson} as const;`);
  }

  const header = `// AUTO-GENERATED by packages/contracts/scripts/export-abi.ts — DO NOT EDIT BY HAND.
// Source: compiled Hardhat artifacts (packages/contracts/artifacts).
// Regenerate with \`npm run export:abi\` in packages/contracts (auto-runs on \`npm run compile\`).
/* eslint-disable */

`;

  const outDir = path.dirname(OUT_PATH);
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }
  fs.writeFileSync(OUT_PATH, header + blocks.join("\n\n") + "\n");

  console.log(`✅ Exported ${CONTRACTS.length} ABIs → ${path.relative(process.cwd(), OUT_PATH)}`);
  for (const name of CONTRACTS) console.log(`   • ${name} → ${constName(name)}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
