/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockFeeRecipientsSol from "./MockFeeRecipients.sol";
export type { mockFeeRecipientsSol };
export type { MockTicketGate } from "./MockTicketGate";
