/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockTicketGateInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "access"
      | "globalAccess"
      | "hasAccessToVideo"
      | "isFilmDelisted"
      | "setAccess"
      | "setDelisted"
      | "setGlobalAccess"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "access",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "globalAccess",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccessToVideo",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isFilmDelisted",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAccess",
    values: [AddressLike, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setDelisted",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setGlobalAccess",
    values: [boolean]
  ): string;

  decodeFunctionResult(functionFragment: "access", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "globalAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasAccessToVideo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isFilmDelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAccess", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGlobalAccess",
    data: BytesLike
  ): Result;
}

export interface MockTicketGate extends BaseContract {
  connect(runner?: ContractRunner | null): MockTicketGate;
  waitForDeployment(): Promise<this>;

  interface: MockTicketGateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  access: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [boolean],
    "view"
  >;

  globalAccess: TypedContractMethod<[], [boolean], "view">;

  hasAccessToVideo: TypedContractMethod<
    [user: AddressLike, videoHash: string],
    [boolean],
    "view"
  >;

  isFilmDelisted: TypedContractMethod<[videoHash: string], [boolean], "view">;

  setAccess: TypedContractMethod<
    [user: AddressLike, videoHash: string, v: boolean],
    [void],
    "nonpayable"
  >;

  setDelisted: TypedContractMethod<
    [videoHash: string, v: boolean],
    [void],
    "nonpayable"
  >;

  setGlobalAccess: TypedContractMethod<[v: boolean], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "access"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "globalAccess"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasAccessToVideo"
  ): TypedContractMethod<
    [user: AddressLike, videoHash: string],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isFilmDelisted"
  ): TypedContractMethod<[videoHash: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "setAccess"
  ): TypedContractMethod<
    [user: AddressLike, videoHash: string, v: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDelisted"
  ): TypedContractMethod<[videoHash: string, v: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGlobalAccess"
  ): TypedContractMethod<[v: boolean], [void], "nonpayable">;

  filters: {};
}
