/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  AcceptingReceiver,
  AcceptingReceiverInterface,
} from "../../../../contracts/mocks/MockFeeRecipients.sol/AcceptingReceiver";

const _abi = [
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f5ffd5b50604480601a5f395ff3fe608060405236600a57005b5f5ffdfea264697066735822122029b036c57a0d62619840bdddfbf00610ff89a34736dd5d523b5a6915d57ba2a364736f6c634300081c0033";

type AcceptingReceiverConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AcceptingReceiverConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AcceptingReceiver__factory extends ContractFactory {
  constructor(...args: AcceptingReceiverConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AcceptingReceiver & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): AcceptingReceiver__factory {
    return super.connect(runner) as AcceptingReceiver__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AcceptingReceiverInterface {
    return new Interface(_abi) as AcceptingReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AcceptingReceiver {
    return new Contract(address, _abi, runner) as unknown as AcceptingReceiver;
  }
}
