/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  RevertingReceiver,
  RevertingReceiverInterface,
} from "../../../../contracts/mocks/MockFeeRecipients.sol/RevertingReceiver";

const _abi = [
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f5ffd5b506101138061001c5f395ff3fe6080604052366041576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040160389060c1565b60405180910390fd5b5f5ffd5b5f82825260208201905092915050565b7f4d6f636b466565526563697069656e74733a2063616e6e6f74207265636569765f8201527f6520455448000000000000000000000000000000000000000000000000000000602082015250565b5f60ad6025836045565b915060b6826055565b604082019050919050565b5f6020820190508181035f83015260d68160a3565b905091905056fea264697066735822122012be8e049ef676fbefff1d7d1277aa148048bab98e1bf0912f4ddbc4750ef71e64736f6c634300081c0033";

type RevertingReceiverConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RevertingReceiverConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class RevertingReceiver__factory extends ContractFactory {
  constructor(...args: RevertingReceiverConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      RevertingReceiver & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): RevertingReceiver__factory {
    return super.connect(runner) as RevertingReceiver__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RevertingReceiverInterface {
    return new Interface(_abi) as RevertingReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RevertingReceiver {
    return new Contract(address, _abi, runner) as unknown as RevertingReceiver;
  }
}
