/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AcceptingReceiver } from "./AcceptingReceiver";
export type { RevertingReceiver } from "./RevertingReceiver";
